### ISSUE TITLE
List of missing TFS features from Cipbia up to version 10.98

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3600]
Just for reference, someone asked me to keep it here too. (for a more in-depth information, refer to [this thread](https://otland.net/threads/tfs-1-x-list-of-missing-tfs-features-from-cipbia.266762/))

## Disclaimer
As I said, **it is just for reference**, it doesn't mean we will be implementing any of it at all, but feel free to make a PR if you want to try.
## Features

- [ ] Implemented the **You cannot use objects that fast.** message if the player use an object more than 2 times per second. [8.72]
- [ ] All players now gain 10 second invisibility to creatures upon login, but as soon as the player has moved or attacked, creatures will again see the character. [9.5]
- [ ] In the case of disconnection from server, players now have a greater chance of survival. [9.5]
- Characters are now ignored by creatures for 30 seconds upon the time the server recognizes the client has lost connection. This leaves less time a character is vulnerable: 30 seconds (knight), 20 seconds (paladin) or 10 seconds (druid/sorcerer). Note that this is invisibility, not invincibility - area attacks will affect the player still.
- [ ] After dying and re-logging your server log is kept. [9.8] #3535 
- [ ] Reward system for bosses. [10.2]
- [ ] The Adventurer's Blessing was introduced. ([more info](https://tibia.fandom.com/wiki/Adventurer%27s_Blessing)) [10.55]
- [ ] Guild Bank. [10.7] #2214 
- [ ] Delayed spawn feature. [10.7]
- [ ] The Loyalty System was introduced. ([more info](https://tibia.fandom.com/wiki/Loyalty_System)) [10.74]
- [ ] The Store is introduced along with its currency Tibia Coins. [10.8]
- [ ] [Gold Pouch](https://tibia.fandom.com/wiki/Gold_Pouch) added [10.97]

completed:
- [x] Lured creatures walk back to their spawn places as soon as they lose their target. [8.7] done at #3604
- [x] The Depot locker was remade ([pic here](https://i.imgur.com/QlxLvzB.png)). It now contains a Depot Chest(vol: 18) (with 18 numbered depot boxes inside, each one hold infinite amount of items, paged each 32 items, and limited only by the depot limit being free or premy), Inbox (where parcels, letters, Market purchases/expired offers, house items go, and you can't move any item inside it/to it). [9.4]
The depot, as in all 18 Depot Boxes, can store a combined total of 2,000 items (Free Accounts) or up to 10,000 items (Premium Accounts).
- [x] Varying Monster Spawn ([more info](https://tibia.fandom.com/wiki/Varying_Monster_Spawn)) [10.5] done at #3605 
- [x] Certain monsters can no longer have their spawn blocked and will spawn even if there is a player in sight. ([list here](https://tibia.fandom.com/wiki/Updates/10.7#Non-Blockable_Creatures)) [10.7] done at https://github.com/otland/forgottenserver/commit/634ac9f63db1317e42917e29b2bd126edbe7a1d0
- [x] Characters log off after a shorter period of time depending on vocation: a knight (or characters of no vocation) will log off after 60 seconds, a paladin 50 and a druid/sorcerer 40. Before, it was 60 seconds for all vocations. done at https://github.com/otland/forgottenserver/commit/68130bce8e5e5354afdf4f0655614688bd2cd5fd

**Comment by marmichalski** [comment]
The list of non-blockable creatures does not include a black knight, this means it's spawn could not be blocked before 10.7. Do you happen to know of an actual list of non-blockable creatures?

**Comment by Zbizu** [comment]
entering level/quest doors gives exhaust now (for offensive spells at least)
